import type {
  AlertItem,
  AppStoreData,
  ChartComment,
  Drawing,
  NewsItem,
  Opinion,
  PatternDef,
  PatternHit,
  Post,
  PriceWatch,
  SymbolMeta,
} from "@/lib/types";
import { defaultColor } from "@/lib/drawings";
import { generateMockCandles } from "@/lib/market-data/mock-adapter";

function buildDemoDrawings(): Drawing[] {
  const symbolId = "kr_005930";
  const candles = generateMockCandles({
    symbolId,
    ticker: "005930",
    timeframe: "D",
    limit: 120,
  });
  if (candles.length < 80) return [];
  const a = candles[Math.floor(candles.length * 0.25)];
  const b = candles[Math.floor(candles.length * 0.45)];
  const c = candles[Math.floor(candles.length * 0.55)];
  const d = candles[Math.floor(candles.length * 0.7)];
  const e = candles[Math.floor(candles.length * 0.8)];
  const now = new Date().toISOString();
  return [
    {
      id: "draw_seed_trend",
      symbolId,
      tool: "trend",
      points: [
        { time: a.time, price: a.low },
        { time: b.time, price: b.high },
      ],
      color: defaultColor("trend"),
      createdAt: now,
    },
    {
      id: "draw_seed_horizontal",
      symbolId,
      tool: "horizontal",
      points: [{ time: c.time, price: c.close }],
      color: defaultColor("horizontal"),
      createdAt: now,
    },
    {
      id: "draw_seed_channel",
      symbolId,
      tool: "channel",
      points: [
        { time: a.time, price: a.low * 0.995 },
        { time: d.time, price: d.low * 1.002 },
        { time: c.time, price: c.high },
      ],
      color: defaultColor("channel"),
      createdAt: now,
    },
    {
      id: "draw_seed_fib",
      symbolId,
      tool: "fibonacci",
      points: [
        { time: b.time, price: Math.max(b.high, d.high) },
        { time: e.time, price: Math.min(e.low, c.low) },
      ],
      color: defaultColor("fibonacci"),
      createdAt: now,
    },
    {
      id: "draw_seed_rect",
      symbolId,
      tool: "rectangle",
      points: [
        { time: c.time, price: c.high },
        { time: e.time, price: e.low },
      ],
      color: defaultColor("rectangle"),
      createdAt: now,
    },
    {
      id: "draw_seed_text",
      symbolId,
      tool: "text",
      points: [{ time: d.time, price: d.high }],
      color: defaultColor("text"),
      text: "데모: 지지 관찰",
      createdAt: now,
    },
  ];
}

export const SEED_SYMBOLS: SymbolMeta[] = [
  {
    id: "kr_005930",
    ticker: "005930",
    exchange: "KRX",
    nameKo: "삼성전자",
    nameEn: "Samsung Electronics",
    assetClass: "kr_stock",
    aliases: ["삼성", "삼전", "Samsung"],
  },
  {
    id: "kr_000660",
    ticker: "000660",
    exchange: "KRX",
    nameKo: "SK하이닉스",
    nameEn: "SK Hynix",
    assetClass: "kr_stock",
    aliases: ["하이닉스", "SKHynix"],
  },
  {
    id: "kr_035420",
    ticker: "035420",
    exchange: "KRX",
    nameKo: "NAVER",
    nameEn: "NAVER",
    assetClass: "kr_stock",
    aliases: ["네이버"],
  },
  {
    id: "us_AAPL",
    ticker: "AAPL",
    exchange: "NASDAQ",
    nameKo: "애플",
    nameEn: "Apple",
    assetClass: "us_stock",
    aliases: ["Apple"],
  },
  {
    id: "us_NVDA",
    ticker: "NVDA",
    exchange: "NASDAQ",
    nameKo: "엔비디아",
    nameEn: "NVIDIA",
    assetClass: "us_stock",
    aliases: ["엔비디아", "NVIDIA"],
  },
  {
    id: "us_TSLA",
    ticker: "TSLA",
    exchange: "NASDAQ",
    nameKo: "테슬라",
    nameEn: "Tesla",
    assetClass: "us_stock",
    aliases: ["테슬라", "Tesla"],
  },
  {
    id: "crypto_BTCUSDT",
    ticker: "BTCUSDT",
    exchange: "BINANCE",
    nameKo: "비트코인",
    nameEn: "Bitcoin",
    assetClass: "crypto",
    aliases: ["비트코인", "BTC", "Bitcoin"],
  },
  {
    id: "crypto_ETHUSDT",
    ticker: "ETHUSDT",
    exchange: "BINANCE",
    nameKo: "이더리움",
    nameEn: "Ethereum",
    assetClass: "crypto",
    aliases: ["이더리움", "ETH", "Ethereum"],
  },
  // Feature ID: symbol.chips — benchmark / thematic pins
  {
    id: "idx_SPX500",
    ticker: "SPX500",
    exchange: "CBOE",
    nameKo: "S&P 500",
    nameEn: "S&P 500",
    assetClass: "us_stock",
    aliases: ["SPX", "S&P500"],
  },
  {
    id: "us_SPY",
    ticker: "SPY",
    exchange: "NYSE",
    nameKo: "SPDR S&P 500",
    nameEn: "SPDR S&P 500 ETF",
    assetClass: "us_stock",
    aliases: ["SPY"],
  },
  {
    id: "us_QQQ",
    ticker: "QQQ",
    exchange: "NASDAQ",
    nameKo: "인베스코 QQQ",
    nameEn: "Invesco QQQ",
    assetClass: "us_stock",
    aliases: ["QQQ"],
  },
  {
    id: "idx_MAG7",
    ticker: "MAG7",
    exchange: "INDEX",
    nameKo: "매그니피센트7",
    nameEn: "Magnificent 7 Basket",
    assetClass: "us_stock",
    aliases: ["MAG7", "Magnificent7"],
  },
  {
    id: "idx_SOX",
    ticker: "SOX",
    exchange: "NYSE",
    nameKo: "필라델피아 반도체",
    nameEn: "PHLX Semiconductor",
    assetClass: "us_stock",
    aliases: ["SOX"],
  },
  {
    id: "us_VNQ",
    ticker: "VNQ",
    exchange: "NYSE",
    nameKo: "뱅가드 리츠",
    nameEn: "Vanguard Real Estate ETF",
    assetClass: "us_stock",
    aliases: ["VNQ"],
  },
  {
    id: "us_VNPA",
    ticker: "VNPA",
    exchange: "OTC",
    nameKo: "VNPA",
    nameEn: "VNPA",
    assetClass: "us_stock",
    aliases: ["VNPA"],
  },
];

export const SEED_NEWS: NewsItem[] = [
  {
    id: "news_01",
    symbolId: "us_NVDA",
    title: "엔비디아, AI 인프라 수요 지속 전망",
    summary: "데이터센터 GPU 수요가 분기 가이던스를 상회할 수 있다는 분석 보고서.",
    source: "ChartDesk Wire (delayed)",
    publishedAt: "2026-09-14T14:30:00.000Z",
  },
  {
    id: "news_02",
    symbolId: "kr_005930",
    title: "삼성전자, HBM 생산 라인 증설 검토",
    summary: "메모리 사이클 회복에 대비한 설비 투자 논의가 재개됐다는 보도.",
    source: "ChartDesk Wire (delayed)",
    publishedAt: "2026-09-13T01:00:00.000Z",
  },
  {
    id: "news_03",
    title: "미 증시 마감 — 나스닥 소폭 상승",
    summary: "기술주 중심 반등. 거래량은 평균 이하 (지연 시세).",
    source: "ChartDesk Wire (delayed)",
    publishedAt: "2026-09-12T20:05:00.000Z",
  },
];

export const SEED_COMMENTS: ChartComment[] = [
  {
    id: "cmt_01",
    symbolId: "crypto_BTCUSDT",
    body: "BTCUSDT 호수 조정이 모두 반해 있습니다.",
    author: "김수내기",
    createdAt: "2026-09-12T06:56:00.000Z",
  },
];

export const SEED_PRICE_WATCHES: PriceWatch[] = [];

export const SEED_POSTS: Post[] = [
  {
    id: "post_surv_01",
    externalUrl: "https://fanding.kr/@easychart/demo-survival-01",
    category: "survival_strategy",
    title: "생존 전략: 이중바닥과 손절 규칙",
    body: "이중바닥이 완성되면 넥라인 돌파 후 분할 진입. 손절은 두 번째 저점 하단. 삼성전자처럼 거래대금이 실린 종목에서만 적용.",
    publishedAt: "2026-08-01T09:00:00.000Z",
    source: "fanding_easychart",
    ingestMethod: "manual_paste",
    symbolIds: ["kr_005930"],
    createdAt: "2026-08-01T09:05:00.000Z",
  },
  {
    id: "post_rt_01",
    externalUrl: "https://fanding.kr/@easychart/demo-rt-01",
    category: "realtime_chart",
    title: "실시간: NVDA 4시간봉 관찰",
    body: "엔비디아 4시간봉에서 단기 이평 골든크로스 시도. 매수보다 관망 후 돌파 확인이 우선. 볼륨이 평균을 넘는지 체크.",
    publishedAt: "2026-09-10T02:00:00.000Z",
    source: "fanding_easychart",
    ingestMethod: "manual_paste",
    symbolIds: ["us_NVDA"],
    createdAt: "2026-09-10T02:10:00.000Z",
  },
  {
    id: "post_mind_01",
    externalUrl: "https://fanding.kr/@easychart/demo-mind-01",
    category: "mindset",
    title: "마인드셋: 손실 허용 범위",
    body: "하루 손실 한도를 넘기면 즉시 종료. 복수매매 금지. 차트 의견은 연구 보조일 뿐 확신이 아니다.",
    publishedAt: "2026-07-15T12:00:00.000Z",
    source: "fanding_easychart",
    ingestMethod: "manual_paste",
    symbolIds: [],
    createdAt: "2026-07-15T12:05:00.000Z",
  },
  {
    id: "post_ins_01",
    externalUrl: "https://fanding.kr/@easychart/demo-ins-01",
    category: "insight",
    title: "인사이트: 반도체 사이클과 SK하이닉스",
    body: "메모리 사이클 회복 테마. SK하이닉스 중기 추세는 우상향이나 단기 과열 구간에서는 분할 접근.",
    publishedAt: "2026-09-01T08:00:00.000Z",
    source: "fanding_easychart",
    ingestMethod: "manual_paste",
    symbolIds: ["kr_000660"],
    createdAt: "2026-09-01T08:05:00.000Z",
  },
  {
    id: "post_rt_02",
    externalUrl: "https://fanding.kr/@easychart/demo-rt-02",
    category: "realtime_chart",
    title: "비트코인 지지선 반응",
    body: "BTCUSDT 일봉 지지 터치 후 반등 시도. 매수 관점이나 거래량 확인 전엔 관망. 손절은 직전 스윙 저점.",
    publishedAt: "2026-09-12T06:00:00.000Z",
    source: "fanding_easychart",
    ingestMethod: "manual_paste",
    symbolIds: ["crypto_BTCUSDT"],
    createdAt: "2026-09-12T06:10:00.000Z",
  },
];

export const SEED_PATTERNS: PatternDef[] = [
  {
    id: "pat_double_bottom",
    name: "이중바닥 (생존 전략)",
    description: "유사 스윙 저점 쌍 + 넥라인 돌파. 비밀 생존 전략 강의 파생.",
    sourcePostIds: ["post_surv_01"],
    timeframes: ["60", "240", "D"],
    rules: [
      { type: "swing_low_pair", params: { tolerancePct: 2 } },
      { type: "neckline_break" },
    ],
    display: { label: "이중바닥?", color: "#38bdf8" },
    alert: { cooldownMinutes: 240 },
    enabled: true,
    dsl: "swing_low_pair tolerancePct=2; neckline_break",
    reviewStatus: "approved",
    extractMethod: "seed",
    learnedAt: "2026-09-09T12:00:00.000Z",
  },
  {
    id: "pat_ma_cross",
    name: "단기 EMA 골든크로스",
    description: "EMA9가 EMA21을 상향 돌파.",
    sourcePostIds: ["post_rt_01"],
    timeframes: ["15", "60", "240", "D"],
    rules: [{ type: "ma_cross", params: { fast: 9, slow: 21 } }],
    display: { label: "EMA크로스", color: "#34d399" },
    alert: { cooldownMinutes: 120 },
    enabled: true,
    dsl: "ma_cross fast=9 slow=21",
    reviewStatus: "approved",
    extractMethod: "seed",
    learnedAt: "2026-09-10T02:00:00.000Z",
  },
  {
    id: "pat_support_bounce",
    name: "지지 반등",
    description: "스윙 저점 지지 터치 후 양봉 반등.",
    sourcePostIds: ["post_rt_02"],
    timeframes: ["60", "240", "D"],
    rules: [{ type: "support_bounce" }],
    display: { label: "지지반등", color: "#fbbf24" },
    alert: { cooldownMinutes: 180 },
    enabled: true,
    dsl: "support_bounce",
    reviewStatus: "approved",
    extractMethod: "seed",
    learnedAt: "2026-09-11T08:00:00.000Z",
  },
  {
    id: "pat_rsi_oversold",
    name: "RSI 과매도 반전 후보",
    description: "RSI(14) < 30 — 반등 후보, 단독 진입 금지.",
    sourcePostIds: ["post_mind_01"],
    timeframes: ["60", "240", "D"],
    rules: [{ type: "rsi_oversold", params: { period: 14, threshold: 30 } }],
    display: { label: "RSI과매도", color: "#fb7185" },
    alert: { cooldownMinutes: 360 },
    enabled: true,
    dsl: "rsi_oversold period=14 threshold=30",
    reviewStatus: "approved",
    extractMethod: "seed",
    learnedAt: "2026-09-08T09:00:00.000Z",
  },
  {
    id: "pat_engulfing",
    name: "상승 장악형",
    description: "음봉 이후 양봉이 몸통을 장악.",
    sourcePostIds: ["post_surv_01"],
    timeframes: ["15", "60", "240", "D"],
    rules: [{ type: "bullish_engulfing" }],
    display: { label: "장악형", color: "#a3e635" },
    alert: { cooldownMinutes: 60 },
    enabled: true,
    dsl: "bullish_engulfing",
    reviewStatus: "approved",
    extractMethod: "seed",
    learnedAt: "2026-09-09T12:05:00.000Z",
  },
  {
    id: "pat_volume_spike",
    name: "거래량 스파이크",
    description: "20봉 평균 대비 2배 이상 거래량.",
    sourcePostIds: ["post_ins_01"],
    timeframes: ["15", "60", "240", "D"],
    rules: [{ type: "volume_spike", params: { mult: 2 } }],
    display: { label: "볼륨↑", color: "#c084fc" },
    alert: { cooldownMinutes: 90 },
    enabled: true,
    dsl: "volume_spike mult=2",
    reviewStatus: "approved",
    extractMethod: "seed",
    learnedAt: "2026-09-12T06:10:00.000Z",
  },
  {
    id: "pat_pending_demo",
    name: "넥라인 돌파 (검수 대기 데모)",
    description:
      "데모: 실제 멤버십 원문을 드롭하면 이런 항목이 검수 큐에 쌓입니다. 승인 전 매칭 비활성.",
    sourcePostIds: ["post_rt_01"],
    timeframes: ["60", "240", "D"],
    rules: [{ type: "neckline_break" }],
    display: { label: "넥라인?", color: "#94a3b8" },
    alert: { cooldownMinutes: 180 },
    enabled: false,
    dsl: "neckline_break",
    reviewStatus: "pending",
    extractMethod: "heuristic",
    learnedAt: "2026-09-15T10:00:00.000Z",
  },
];

export const SEED_OPINIONS: Opinion[] = [
  {
    id: "op_01",
    symbolId: "us_NVDA",
    direction: "watch",
    confidence: "medium",
    summary: "엔비디아(NVDA) — 관망 초안",
    rationale: [
      "NVDA 단기 EMA가 장기 EMA 상단 근처 — 돌파 확인 대기",
      "실시간 분석: 골든크로스 시도, 볼륨 확인 우선",
    ],
    risks: [
      "손절 기준을 미리 정했는지 확인하세요.",
      "포지션 크기가 계좌 대비 과도하지 않은지 점검하세요.",
    ],
    sourcePostId: "post_rt_01",
    category: "realtime_chart",
    status: "approved",
    createdAt: "2026-09-10T02:15:00.000Z",
    reviewedBy: "local-user",
    reviewedAt: "2026-09-10T02:20:00.000Z",
  },
  {
    id: "op_02",
    symbolId: "crypto_BTCUSDT",
    direction: "buy",
    confidence: "low",
    summary: "비트코인(BTCUSDT) — 매수 관점 초안",
    rationale: [
      "지지 터치 후 반등 시도",
      "거래량 확인 전 분할만 검토",
    ],
    risks: [
      "하루 손실 한도를 넘기면 즉시 종료.",
      "차트 의견은 연구 보조일 뿐 확신이 아니다.",
    ],
    sourcePostId: "post_rt_02",
    category: "realtime_chart",
    status: "draft",
    createdAt: "2026-09-12T06:15:00.000Z",
  },
];

export const SEED_ALERTS: AlertItem[] = [
  {
    id: "alert_01",
    type: "opinion",
    title: "검수 대기 의견",
    message: "BTCUSDT 매수 초안이 검수 큐에 있습니다.",
    symbolId: "crypto_BTCUSDT",
    opinionId: "op_02",
    firedAt: "2026-09-12T06:16:00.000Z",
    read: false,
  },
];

export function createSeedStore(): AppStoreData {
  return {
    symbols: SEED_SYMBOLS,
    posts: SEED_POSTS,
    opinions: SEED_OPINIONS,
    patterns: SEED_PATTERNS,
    patternHits: [] as PatternHit[],
    drawings: buildDemoDrawings(),
    alerts: SEED_ALERTS,
    watchlist: ["kr_005930", "us_NVDA", "crypto_BTCUSDT", "kr_000660"],
    priceWatches: SEED_PRICE_WATCHES,
    comments: SEED_COMMENTS,
    news: SEED_NEWS,
    technicalAlerts: [],
    webhookConfig: { url: "", enabled: false },
  };
}
